name: 'Replace Keywords in Comments'
description: 'Replaces :compliment: and :insult: in issue comments with custom text.'
inputs:
  comment-body:
    description: 'The body of the comment to process.'
    required: true
  language:
    description: 'The language to use for the custom text.'
    default: 'en'
    required: false
  language-file:
    description: 'The file containing the custom text.'
    default: ''
    required: false
outputs:
  updated-body:
    description: 'The updated comment body with keywords replaced.'
runs:
  using: 'node20'
  main: 'index.js'