name: Build project

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: distribution
          path: dist

  update:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: distribution
          path: dist

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update distribution
          title: Update distribution
          reviewers: Bellangelo
          branch: bot-action-update-distribution