name: Replace Keywords with Compliments and Insults

on:
  issue_comment:
    types: [created, edited]

jobs:
  replace-keywords:
    if: github.actor != 'github-actions[bot]' # Ensure that the action isn't triggered by the bot itself
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run the Node.js action to replace keywords
        uses: ./
        with:
          comment-body: "${{ github.event.comment.body }}"
          comment-id: ${{ github.event.comment.id }}